#!/bin/sh

# 清除tex的中间文件
# 不推荐使用本脚本了，
# 可以用 `latexmk -c tex源文件名` 命令替代。

# Deprecated!
# `latexmk -c texfile` seems good enough.

rm -f \
	*.nav \
	*.snm \
	*.aux \
	*.bbl \
	*.blg \
	*.dvi \
	*.glo \
	*.gls \
	*.idx \
	*.ilg \
	*.ind \
	*.ist \
	*.log \
	*.out \
	*.ps \
	*.thm \
	*.toc \
	*.lof \
	*.lot \
	*.loe \
	*.bcf \
	*.run.xml
